### PR TITLE
CI: Add GitHub Actions workflows

### PR DESCRIPTION
**Pull request by algernon**
This is based on @obra's earlier work, and adds GitHub Actions workflows. At the moment, this is not 100% complete yet, there's a few regressions compared to the Travis-based build, some of which can be fixed, some cannot. The release process documentation has already been updated to reflect the migration.

## TODO:

- [x] Linter steps run. (This is new compared to Travis!)
- [x] Compiles and builds for macOS, Windows and Linux/amd64.
- [x] Non-tagged builds do not end up with a public artifact to download.
- [x] Publishing artifacts works too (tested elsewhere to reduce clutter here).
- [ ] macOS signing set up.

## Regressions

- Linux/arm64 build. There is no Linux/arm64 builder provided by GitHub, so this may be a regression we need to live with.
- We no longer publish artifacts for non-master builds

Since there's no Linux/arm64 builder provided by GitHub, I think we'll be losing that for now. To keep the workflow reasonable, I also didn't implement artifact publication for non-master builds. That's something we may eventually want, but it's not _that_ important right now, I believe.

## Nice to have

I can see a couple of things being easier to automate with this system:

- [x] A script to automate the release:
  - Verify that NEWS entries exist for the version to be released.
  - Prompt for the user to verify that `Chrysalis-Firmware-Bundle` is up to date.
  - Update the shipped firmware files using `tools/update-firmware`, and commit the results.
  - Set the version in `package.json` to what's provided on the command line.
  - Set the release date in `NEWS.md`.
  - Commit both changes as `Preparations for Chrysalis ${version}`.
  - Create a draft release on GitHub, with the appropriate parts of the NEWS file.
  - Tag the tree, and push the changes and the tag.
- [x] A script to switch to a snapshot
  - Bump the version in `package.json` to `x.y.(z+1)-snapshot`.
  - Commit the change as `Bump version to x.y.(z+1)-snapshot`.
  - Create a pre-release on GitHub.
  - Push the changes.

### CODE REVIEW

**Comment by algernon** [comment]
Pushed two scripts that should aid us in the release process. They aren't fully tested yet, I only did partial tests in a different repo & locally, but they _should_ work, for the most part.

So the major missing feature is macOS signing. That's something I have zero experience with, but according to the electron-builder docs, that should be reasonably easy to add.

**Comment by algernon** [comment]
Oh, by the way: this will also make the following scripts obsolete:

- `tools/get-artifact`
- `tools/s3-upload.js` and `tools/s3-upload.js.orig` (the latter of which should be removed anyway)

It possibly makes `tools/add-osx-cert.sh` obsolete too.

We could also improve the `tools/release/release.sh` script to ask us whether the screenshot is up to date, too. We can't automatically create one, because if there's no Chrysalis running, we need to start one, and connect to a keyboard to have something interesting on the screenshot - and we can't do that automatically (yet?).

**Comment by obra** [comment]
Is there a reason not to have this merged and then iterate?

**Comment by algernon** [comment]
To be honest - no, there isn't. We can iterate over it before we cut another release. I'm graduating it out of draft state.

**Pull request merged**
