### PR TITLE
Update copyright years & make our @ imports more consistent

### PR DESCRIPTION
**Pull request by algernon**
This has two parts: the first updates all the copyright years, and adds the copyright header to files that were missing it.

The more interesting one is the second part, which changes a whole lot of imports to use `@api`, `@main` or `@renderer` instead of relative imports. There are a few cases where I changed an existing `@renderer` import to a relative one, because the guiding principle was that stuff that will move together, stuff that forms a logical unit, should use relative imports when importing things from the same unit. When importing from outside the logical unit, then we use the aliases.

### CODE REVIEW

**Comment by obra** [comment]
Did you do the alias cleanups manually or is there a tool?

**Comment by algernon** [comment]
I did them manually. I could have looked for, or written a tool, but I felt that what should be a relative import, and what should use an alias is not something that's easily automated.

**Comment by obra** [comment]
I'm a little iffy on the relative imports, but not enough to say not to merge this. 

As a related task, at some point, I want to let vscode's react import cleanup refactoring rules clean up the order and formatting of all our imports, but that's not urgent.

**Comment by algernon** [comment]
I don't have very strong opinions either. This felt "right", but I can be easily swayed. We can always iterate on it further.

Rearranging the imports with an automatic tool would be great. They are a bit of a mess now.

**Pull request merged**
