### PR TITLE
Firmware upgrade/redesign

### LINKED ISSUE #533: way to identify firmware version currently on device
**Is your feature request related to a problem? Please describe.**
Not so much a problem as a small annoyance.
I have no way to know which firmware is currently running on my Keyboardio (flashed from Chrysalis). For example the version, `0.7.7` vs `0.7.6`, or `default` vs `experimental`.

**Describe the solution you'd like**
Some kind of indication of what was last flashed to the device.
For example:
-  `0.7.7 experimental`
-  `0.7.6 default`

**Describe alternatives you've considered**
Writing down or remembering what I did last.

**Additional context**
I know there will be complications with custom firmware bundles.

### PR DESCRIPTION
**Pull request by algernon**
There were multiple complaints against the firmware update screen, and this redesign addresses most of them. The goal was to simplify the screen, reduce the amount of unnecessary information displayed at a time, while also showing useful information we did not show before.

## The main Firmware Update screen

Screenshot from 2022-06-26 19-19-47

With this redesign, the update instructions are no longer shown directly on the firmware update screen. Instead, when one selects the "Upload" or "Factory reset" actions, the popup dialog will show the instructions instead. Previously, clicking on "Upload" started the process immediately without confirmation - now we ask for confirmation in this case too. Both in order to be able to display the instructions, and to avoid accidentally triggering the process. See below for additional screenshots.

Then, the dropdown that was used to select the firmware to use has been replaced by a group of radio buttons. We only ever have three choices: the current firmware (for which a version is shown now, if available), the firmware Chrysalis ships with, or a custom one. Having all options visible at the same time presents useful information, and is easier to navigate than a dropdown. It also presented a great opportunity to display the running firmware version, which fixes #533.

Another bit of information that wasn't strictly necessary to see all the time is the link to the firmware sources. Since we have a "View firmware changes" button now, the link to the firmware sources was moved to the changelog dialog.

A much smaller - but still important - change is that doing a factory reset as part of the update is now its own button, rather than a checkbox. This way it can simply be clicked, rather than requiring ticking a checkbox and then clicking "Update". It also makes the "Update" button's action straightforward, it always does the same thing: updates the current firmware. It no longer depends on external state to significantly alter its behaviour. It's only important input is the firmware to flash.

## Update

Screenshot from 2022-06-26 19-19-28

## Factory reset

Screenshot from 2022-06-26 19-19-34

## Firmware Changes

Screenshot from 2022-06-26 19-19-40

# Other notes

Other than an UI overhaul, this PR implements another important change: Moving the Factory Reset handling to `api/flash`, rather than trying to drive it from the frontend. Our factory reset + firmware update combo has been broken for a while, moving it to `api/flash` allowed me to fix it in a sane, and reliable way.

As an added benefit, the steps displayed are now correct in both cases.

### CODE REVIEW

**Comment by algernon** [comment]
FWIW, I have a couple of other pending changes related to flashing, mostly in the backend parts. But they depend on moving the factory reset there. Those changes will have much smaller UI impacts than this, so I'm submitting these parts separately.

They are - I believe - a net improvement overall.

**Comment by obra** [comment]
Tweaked the display a bit.  Multiline listItemText really isn't a great fit for what we're doing.

I noticed that the device-specific instructions don't seem to be working.

**Comment by algernon** [comment]
> Tweaked the display a bit. Multiline listItemText really isn't a great fit for what we're doing.

I thought they looked nice, and a similar pattern is used in Chrome's settings in a few places too:

### Clear browsing data
Screenshot from 2022-06-28 08-16-43

### Cookie settings

Screenshot from 2022-06-28 08-17-21

`Latest: <version>` in the same font, same color, with the "What's new?" button right after feels crowded. 

In contrast, having them on two lines, with the version in secondary color adds an - I believe - useful emphasis: the latest version is the more important bit, the version itself is useful, but not essential (ie, secondary) information, displayed as such.

> I noticed that the device-specific instructions don't seem to be working.

Those should be working the same as they did before, except hidden behind the Update / Factory Reset buttons. Mind you, if you run `yarn run start`, and it hot-reloads, then the instructions won't be properly updated. Disconnecting and reconnecting to the keyboard should update the instructions, however.

**Comment by algernon** [comment]
The title + version + button on the same line thing is not something I'm comfortable with.

I really like how the Chrome cookie settings look, and a similar pattern here, in my opinion, would work great: 

```
o Latest firmware
  0.10.3-snapshot
  
      The latest version of the firmware as shipped with Chrysalis, usually comes with bug fixes
      and all kinds of improvements. You can view the full list of changes [here].

o Choose a local firmware build
  [filename]

      You can flash a custom built firmware too, if you want to fully customize your keyboard. As long 
      as the essential plugins are included, Chrysalis will work fine with it, too. You can read more about 
      building your own firmware [here].
```

I think that'd be a whole lot nicer than what either of us proposed so far.

**Comment by obra** [comment]
( I agree that the two line list items looked elegant the way you had them. My grumble is that the component doesn’t let us shove widgets into the “text” sections. )

**Comment by algernon** [comment]
What kind of widgets would you want in the text sections?

**Comment by obra** [comment]
Specifically, I'd wanted to be able to shove the "changelog" button inside
the text section. But I'm going to try implementing your suggestion above.

**Pull request merged**
