### PR TITLE
Issue 609 nonexistent layers

### PR DESCRIPTION
**Pull request by MagicKriss**
Fix for bug https://github.com/keyboardio/Chrysalis/issues/609 - "Chrysalis + Atreus +  Move to layer exposes nonexistent layers"

Husky's pre-commit hooks would nag me about another file I didn't touch, so I ran prettier.

### CODE REVIEW

**Comment by obra** [comment]
Thanks!

@algernon can you please review tomorow?

**Review by algernon — CHANGES_REQUESTED** [review]
This looks good for the most part (thank you!), there's one thing that I think isn't quite ok: with this change, with removing the `min`/`max` properties from the target layer `<Input>` element, the user would be able to - seemingly - set a layer that doesn't exist, because the index gets clamped down to fit into the interval in `onTargetLayerChange`.

Instead, we should still have the `min`/`max` on the input, but use `getMaxLayer` to set `max`. Other than this, approved.

Since this is a fairly annoying problem, I can merge this as-is, and patch it up post-merge.

**Comment by MagicKriss** [comment]
@algernon I have added back max/min. Please take a look

**Review by algernon — APPROVED** [review]
Perfect, thank you!

**Pull request merged**
