### PR TITLE
Implement an auto-update mechanism

### LINKED ISSUE #886: Auto update
For 1.0 we should support autoupdate. These days, I believe it’s largely just something we need to enable.

### PR DESCRIPTION
**Pull request by algernon**
This replaces the old, fragile, latest version notification on the menubar with an auto-upgrade mechanism.

While it is the main process that does the update, it is the renderer that initiates it. We do this so that we have better control over the process, and can display notifications on the renderer, without race conditions.

The renderer orchestrates the process via the `useAutoUpdate` hook, called by the `App`. The hook itself will first tell the main process to check for updates, which in turn will result in an `update-available` event being fired, if there's an update. That event will get sent forward to the renderer as `auto-update.update-available`, and the hook will display a toast. We handle the rest of the upgrade process similarly, the main process pushing new notifications to the renderer.

Because we don't want to force updates on everybody, the feature is opt-in, and there's a new section in the User Interface tab of Preferences to enable the feature.

Fixes #886.

### CODE REVIEW

**Comment by algernon** [comment]
Preview:

https://user-images.githubusercontent.com/17243/172875797-b690d7b3-7608-4f66-b495-da08262be601.mp4

There are currently a few limitations, which I believe are out of scope for this PR, but things we can address later:
- We do not support auto-update for snapshot releases, because electron-builder's electron-updater insists on a substantially different workflow for that than what we have now, one that I'm not convinced is suitable for us.
- There is no way to cancel a download once it started.
- Windows upgrades will not work until #927 is fixed.

I performed some rudimentary tests on Linux with AppImage and that worked like a charm. I have not tried macOS yet, but I expect that to work too. Mind you, testing this currently is a bit unintuitive, because we don't have previous releases that had the necessary files attached to them. Those files will be attached for future releases (the change is on master), so if we cut a 0.10.2 release before merging this, then we'll be able to test whether we can upgrade to .2, simply by rolling the version back locally and building a package.

**Comment by algernon** [comment]
I just tested this with .2: Set the version in `package.json` to 0.10.1, built an AppImage, and ran it. It discovered that .2 is available, and successfully updated. Will test on macOS later today, too.

**Comment by algernon** [comment]
Darn, can't easily test the macOS path yet, because I misunderstood the documentation, and we need a .zip file for mac too, along with the .dmg. Luckily, I have a Minio server set up, so I'll cheat.

**Comment by obra** [comment]
Switching to zips is easy!

       "target": {
-        "target": "dmg",
-        "arch": [
-          "universal"
-        ]
+        "target": "zip",
+        "arch": ["universal"]
       }

**Comment by algernon** [comment]
Yeah, I know! (We need both, btw)

I just need to upload the zip and the dmg to my Minio server, and that involves fighting with macOS. :)

**Comment by obra** [comment]
> We do not support auto-update for snapshot releases, because electron-builder's electron-updater insists on a substantially different workflow for that than what we have now, one that I'm not convinced is suitable for us.

Can you talk more about this?

How are snapshots not just a second parallel release "channel"?

**Comment by algernon** [comment]
They would be, but electron-updater only considers versions with `alpha` and `beta` in them as pre-releases. There's some code in there that is supposed to handle custom tags, but in practice, it doesn't get used. On top of that, it really wants to have separate tags for each pre-release, so we'd have to have a tag for every commit if we wanted to continue with auto-building on every commit.

**Comment by algernon** [comment]
One thing this PR doesn't do yet, is remove translations that were made obsolete. It should do that, too.

**Comment by algernon** [comment]
Rebased on top of master, and it now removes the obsolete strings from the translation files, too.

**Pull request merged**
