### PR TITLE
Implement a firmware file auto-update mechanism

### LINKED ISSUE #952: Decouple firmware releases from Chrysalis
At the moment, if we want to update the firmware Chrysalis ships with, we have to cut a new release. While this is fine for now, once we're hitting the 1.0 milestone, it would be preferable if we could push firmware updates without having to do a new Chrysalis release.

We could do something similar to auto-update, and upon startup, reach out to the release page of Chrysalis-Firmware-Bundle, and see if there's a newer release. If there is, we could grab the firmware and the changelog, and offer to flash either the built-in firmware, or the new version when on the Firmware Upgrade page.

Chrysalis would still ship with firmware included, and we'd update them regularly, whenever we'd release Chrysalis anyway. But we'd be able to push new firmware releases without having to release Chrysalis aswell.

### PR DESCRIPTION
**Pull request by algernon**
Modeled after the application update mechanism, the firmware file auto-update works in a similar way: if the feature is enabled (it is disabled by default), it will check what's the latest version of the firmware on GitHub, and if it's more recent than the version we ship with, and more recent than whatever we have previously downloaded (if anything), then it will download the new bundle and extract it.

The Firmware Update screen will ask the main process for the version, changelog, and base directory to use for the default firmware. If firmware auto-update is enabled, the main process will check first try the downloaded files, and only fall back to the shipped version if we have nothing downloaded yet.

If firmware auto-update is disabled, then we won't even check if there's a new version, because we'll almost always have an update, and we do not want to spam notifications on every single startup.

Fixes #952.

### Preferences

Screenshot from 2022-07-10 12-54-49

### Firmware Update screen

Screenshot from 2022-07-10 12-55-02

### Firmware Changelog

Screenshot from 2022-07-10 12-55-07

## Notes

Firmware bundles are downloaded at app start time (if the feature is enabled), or whenever the setting is toggled on. Once downloaded, Chrysalis will not hit the network again, and will use the local files instead. Thus, the FirmwareUpdate screen renders as fast as previously, because all the data is available locally by that time.

I intentionally made it so that when firmware auto-update is enabled and the bundle has been downloaded, the shipped version is not shown anywhere. I originally showed both (+ custom), but that made the screen very crowded, and it felt unnecessary. Disabling the firmware auto-update will result in the shipped firmware being shown again, so one can downgrade to that, if need be, with little extra work.

### CODE REVIEW

**Comment by obra** [comment]
How does this handle not being online or not being able to connect to github? Is it silent or does it warn or does it error?

**Comment by algernon** [comment]
...I didn't test that. It probably displays an error in a notification. It shouldn't crash or become unusable.

However, I think that in this case, the best course of action would be to silently ignore not being able to check github. If you agree, I'll go ahead and make it so.

**Comment by algernon** [comment]
Force-pushed an update that handles errors better: if anything goes wrong, that will get properly logged. The only time we display an error in the renderer is when we already displayed a notification about an update being available, and an error occurred after. We do not display the reason, but log (hopefully) useful info nevertheless.

A few scenarios:

- We can't contact github: logged & no notification in the renderer
- We can contact github, but it returns a non-200 status: logged & no notification
- We can contact github, but fail to parse the data: logged & no notification
- We fetched the latest info: logged & notification shown
- We fetched the latest info, but downloading the update fails for whatever reason: logged & error notification shown

The firmware update screen does not display a banner yet if the firmware update failed, I'm trying to figure out how to do that best. At the moment, the firmware update screen has zero knowledge about firmware updates, that is all transparently handled by the main process. I suppose we'd need to push the warning-state to the global context. I'll do that next.

**Comment by algernon** [comment]
Screenshot from 2022-07-20 13-56-48

**Comment by obra** [comment]
Can you update the message to: "Chrysalis was unable to check for a new
firmware version. A newer version may be available online."?

**Comment by algernon** [comment]
I can, done!

**Pull request merged**
